# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgUbIphZEKrUu0JasAEvZh91kNT3ApnT
"""

import numpy as np
import networkx as nx
import torch as tc
import torch_geometric as tg
import sys
from src.datasets import NetworkDataset
from src.automata import LLNA
from src.simulation import *



'''
This function two binary matrices which M1 is an NxN square matrix
and M2 is an Nx1 matrix
The usual sum was substituted by the module 2 sum (XOR operation)
'''
def matrix_multiplication(M1, M2):
    # Check if dimensions are compatible for multiplication
    if len(M1[0]) != len(M2):
        print("Error: the number of columns in M1 must be equal to the number of rows in M2.")
    else:
        # Get the dimensions of M1 and M2
        N = len(M1)
        M = len(M2[0])

        # Initialize the result matrix with zeros
        result = np.zeros((N, M), dtype=int)

        # Perform multiplication with sum modulo 2 (XOR)
        for i in range(N):
            for j in range(M):
                sum_module2 = 0
                for k in range(len(M1[0])):  # Iterate over columns of M1 or rows of M2
                    # Binary product and accumulation with XOR
                    sum_module2 ^= (M1[i][k] & M2[k][j])
                result[i][j] = sum_module2

        return result


'''
This function calculates the Boolean derivative.
Checks whether the state change of node x_j can result in the state change of node x_i in the next step.

    Parameters:
    - E (tc.Tensor): The edge tensor.
    - state (tc.Tensor): The state tensor of the nodes.
    - resolution (int): The resolution of the model.
    - x_i: The destination node.
    - x_j: The node whose state will change.

    Returns:
    int: 1 if changing the state of x_j results in changing the state of x_i, 0 otherwise.
'''
def boolean_derivative(E: tc.tensor, state: tc.tensor, x_i, x_j, resolution):
    # Check if x2 is a neighbor of x1
    if (x_i, x_j) in E:
        model = LLNA(resolution)
        # Original state of node x_i
        original_state_xi = model.step(E, state)[x_i]

        # Change the state of x_j
        new_states = state.clone()
        new_states[x_j] ^= 1  # Complements the state of x_j

        # New state of node x_i
        new_state_xi = model.step(E, new_states)[x_i]

        # Checks if there has been a change in the state of x_i
        return int(original_state_xi != new_state_xi)
    else:
        return 0

'''
This function calculates the Jacobian
Parameters:
- E (tc.Tensor): The edge tensor
- state (tc.tensor): the state tensor of the nodes at step t
- N (int): number of nodes --> NxN is the dimension of the Jacobian matrix
resolution (int): The resolution of the model
'''
def jacobian(N, E: tc.tensor, state: tc.tensor, resolution):
    J = tc.zeros((N, N)) #initialize the matrix with zeros
    for i in range(N):
      for j in range(N):
        j
        k = boolean_derivative(E, state, i, j, resolution)
        if k == 1:
          J[i,j] = 1

    return J


'''
Here, we calculate the Lyapunov exponent on Tangent Space
Parameters:
- E (tc.Tensor): The edge tensor
- x0 (tc.tensor): the state tensor of the nodes at step t
- N (int): number of nodes --> NxN is the dimension of the Jacobian matrix
- resolution (int): The resolution of the model
- T (int): number of steps
- Initial_condition_numb (int): initial condition index in H tensor
'''
def tangent_space(N, E: tc.tensor, x0: tc.tensor, resolution, T, initial_condition_numb):
  '''
  We need of the Yt matrix. The Yt matrix is Yt = J*Y_{t-1} envolved after T steps
  beggining at t = 0 with Y0, which is the indentity matrix representing N
  orthogonal perturbations
  '''
  def Y(N, E: tc.tensor, x0: tc.tensor, resolution, T, initial_condition_numb, H):
    Y0 = tc.eye(N)  #Y at step 0
    Yt_ = Y0  #Y at step t - 1
    for t in range(1,T):
      state = H[initial_condition_numb, t]  #Get the state vector at step t
      J = jacobian(N, E, state, resolution)  #calculates the Jacobian
      Yt = matrix_multiplication(J,Yt_)   #envolve Y
      Yt_ = Yt  #Update Yt_
    return Yt

  def lyapunov_spectrum(N, E: tc.tensor, x0: tc.tensor, resolution, T, initial_condition_numb, H):
    Yt = Y(N, E, x0, resolution, T, initial_condition_numb, H)
    Gamma = matrix_multiplication(Yt, Yt.transpose(0, 1))  #Let be Gamma = Yt*(Yt)^T, which (Yt)^T is the transpose of Yt
    eigenvalues, eigenvectors = tc.linalg.eig(Gamma)   #Eigenvalues and Eigenvectors of Gamma
    # Extract only the eigenvalues ​​(real part)
    _lambda = eigenvalues.real
    #Calculation of the Lyapunov spectrum
    lyapunov = []
    for lambda_i in _lambda:
      L = (1/T)*tc.log(lambda_i)
      lyapunov.append(L)
    #plotting the Lyapunov Spectrum
    import matplotlib.pyplot as plt
    x = [i for i in range(1,len(lyapunov)+1)]
    plt.ylabel("Eigenvalues")
    plt.xlabel(f"$\lambda$")
    plt.bar(x, lyapunov)
    plt.title("Lyapunov spectrum")
    plt.show()
    print("Lyapunov exponent in Tangent Space: ",max(lyapunov)) #The maximum Lyapunov exponent determines whether or not the system behaves chaotically

  model = LLNA(resolution)
  H = model.forward(E, x0, T) #Getting the TEPs tensor
  lyapunov_spectrum(N, E, x0, resolution, T, initial_condition_numb, H)


'''
Here, we calculate the Lyapunov exponent over the configuration space. We need calculate the difference pattern vector (Δ),
then, envolve them at time by the Jacobian.
Parameters:
- E (tc.Tensor): The edge tensor
- x0 (tc.tensor): Initial state vector, the state tensor of the all nodes at step t
- dx (tc.tensor): perturbation's vector. It has dimension N, and all its elements are zero,
except the one associated with the defected node which is one.
- N (int): number of nodes --> NxN is the dimension of the Jacobian matrix
- resolution (int): The resolution of the model
- T (int): number of steps
- Initial_condition_numb (int): initial condition index in H tensor
'''
def configuration_space(N, E: tc.tensor, x0: tc.tensor, dx: tc.tensor, resolution, T, initial_condition_numb):
  '''
  Let's calculate the difference pattern vector at step 0:
  ∆x = f(x0) ⊕ f(x0 ⊕ dx). f is the state vector (vector s, in some notations)
  '''
  def Delta0(x0: tc.tensor, dx: tc.tensor):
    g = x0 ^ dx #f(x0 ⊕ dx)
    D0 = x0 ^ g
    return D0

  '''
  Just like the calculations in the tangent space, in the configuration space
  the dynamics is also given by the multiplication of the Jacobian
  Parameter:
  - Delta_0 (tc.tensor): difference pattern vector at step 0
  '''
  def time_evolution(N, E: tc.tensor, x0: tc.tensor, dx: tc.tensor, resolution, T, Delta_0: tc.tensor, initial_condition_numb, H: tc.tensor):
    D_prev = Delta_0 #Initializing at step zero
    for t in range(T):
      state = H[initial_condition_numb, t]
      D = matrix_multiplication(jacobian(N, E, state, resolution), D_prev)
      D_prev = D #update D_prev
    return D

  '''
  Finally, we can calculate the Lyapunov exponent
  '''
  def lyapunov(N, E: tc.tensor, x0: tc.tensor, dx: tc.tensor, resolution, T, initial_condition_numb, H: tc.tensor):
    Delta_0 = Delta0(x0, dx)
    Delta_t = time_evolution(N, E, x0, dx, resolution, T, Delta_0)
    Delta_t_module = sum(Delta_t)
    Delta_0_module = sum(Delta_0)
    L = (1/T)*tc.log(Delta_t_module/Delta_0_module)
    print("Lyapunov Exponent in Configuration Space: ",L)

  model = LLNA(resolution)
  H = model.forward(E, x0, T) #Getting the TEPs tensor
  lyapunov(N, E, x0, dx, resolution, T, initial_condition_numb, H)


#Implementation
dataset = NetworkDataset(path='data/graphs', cached=False)
E, h0 = dataset[10]
resolution = 4
N = 100
T = 50   #Fifty steps
W = 5 #Five initial conditions
'''
Creating a perturbation vector with a defect in node 0
'''
dx = tc.zeros(N)
dx[0] = 1
for initial_condition_numb in range(W):
    tangent_space(N, E, h0[initial_condition_numb], resolution, T, initial_condition_numb)
    configuration_space(N, E, h0[initial_condition_numb], dx, resolution, T, initial_condition_numb)